server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:8001/test_db
    username: root
    password: abcd1234!!QQ
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true

variables:
  backend-url: http://localhost:8080/rest/restapi
  auth-key:
    username: admin
    password: yw9+5.Y-'$5ARVj7S'hm2:RM